language: node_js
node_js:
    - 0.10
    - 0.12

# Special config for Chrome on Travis-CI
before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
